In [1]:
import torch

In [6]:
# Создайте случайный FloatTensor размера 3x4x5
a_tensor = torch.randn(3, 4, 5)

In [7]:
# Выведите его форму (shape)
a_tensor.shape

torch.Size([3, 4, 5])

In [8]:
# Приведите его к форме 6 X 10
b_tensor = torch.reshape(a_tensor, (6, 10))
b_tensor.shape

torch.Size([6, 10])

In [20]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементноb_tensor
v =  torch.randint(10, size=(10,)) # torch.rand(10)
v

tensor([5, 2, 8, 1, 6, 1, 4, 2, 0, 3])

In [21]:
torch.mul(b_tensor, v)

tensor([[  6.9038,  -0.0977, -10.6348,  -1.5213,   5.0069,   0.3300,   2.3989,
           0.5024,   0.0000,  -2.1348],
        [ -5.5345,  -1.9946,  -3.0497,  -0.2911,  -0.3949,   1.0096,   2.7042,
          -0.6390,   0.0000,   2.8992],
        [  3.5390,   1.7484,  21.8641,   0.4255,  -4.4230,   1.0640,   4.2692,
           1.6132,   0.0000,   2.1541],
        [  1.1668,  -0.2264,   4.7359,   0.7087,  -1.6776,   1.3363,   1.8974,
          -0.4299,   0.0000,  -1.5641],
        [ -0.3535,   0.6810,   0.3041,  -0.6642,   2.1460,   1.5397,  -1.5664,
           1.6130,   0.0000,   3.1329],
        [  2.5350,  -0.3532,   2.6782,  -0.9642,  12.5289,  -1.8941,   1.3747,
           3.6695,   0.0000,   0.6356]])

In [27]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
b_tensor.mm(b_tensor.reshape(10, 6))

tensor([[ 0.9067,  1.7058, -0.8273, -5.2258, -3.6837,  0.6858],
        [ 1.8711, -1.4016,  2.2807,  3.1910,  0.7643,  1.2635],
        [ 6.3388, -1.5940,  2.3047,  3.3182,  2.5425, -0.7814],
        [ 2.1273,  2.1710,  1.3356, -0.0597,  1.3633,  0.7322],
        [ 4.5602, -1.0003,  2.3251,  3.7626, -0.0253,  0.7454],
        [ 1.2434,  1.4300,  1.5298,  1.9240,  2.2010, -1.2127]])

In [11]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1, 0.5, 2], requires_grad=True)
z = x**3 + x - 75*x
z.backward(x)
x.grad

tensor([ -71.0000,  -36.6250, -124.0000])

In [6]:
# Создайте единичный тензор размера 5x6
c = torch.ones((5, 6))

In [7]:
# Переведите его в формат numpy
c.numpy()

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)

In [23]:
# Давайте теперь пооптимизируем: возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 
from torch.autograd import Variable


def function(x, w1):
    return x**w1 - 2 * x**2 + 5

def gradient(x):
    return torch.autograd.grad(function(x, w1), x)[0]

w1 = 3
x = Variable(torch.Tensor([2]), requires_grad=True)
learning_rate = 0.01
num_iterations = 120
for i in range(num_iterations):
    x_grad = gradient(x)
    x.data -= learning_rate * x_grad
    if not i%10:
        print(f"Iteration {i+1}, x = {x.data[0]:.2f}, y = {function(x.data[0], w1):.2f}")

Iteration 1, x = 1.96, y = 4.85
Iteration 11, x = 1.69, y = 4.12
Iteration 21, x = 1.55, y = 3.92
Iteration 31, x = 1.47, y = 3.85
Iteration 41, x = 1.42, y = 3.83
Iteration 51, x = 1.39, y = 3.82
Iteration 61, x = 1.37, y = 3.82
Iteration 71, x = 1.36, y = 3.82
Iteration 81, x = 1.35, y = 3.82
Iteration 91, x = 1.34, y = 3.82
Iteration 101, x = 1.34, y = 3.81
Iteration 111, x = 1.34, y = 3.81
